'use strict';
// Run with: NODE_PATH=/path/to/jsdom/node_modules node test/ui.cjs
const {JSDOM}=require('jsdom');const assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),vm=require('node:vm');
const root=path.join(__dirname,'../dist');const dom=new JSDOM(fs.readFileSync(path.join(root,'index.html'),'utf8'),{url:'https://langlab.example/',runScripts:'outside-only',pretendToBeVisual:true});const w=dom.window,blobs=new Map(),downloads=[];let id=0;
w.Blob=Blob;w.TextEncoder=TextEncoder;w.scrollTo=()=>{};w.confirm=()=>true;w.fetch=async name=>({ok:true,text:async()=>fs.readFileSync(path.join(root,name),'utf8')});
w.URL.createObjectURL=blob=>{const url='blob:test-'+(++id);blobs.set(url,blob);return url;};w.URL.revokeObjectURL=()=>{};
w.HTMLAnchorElement.prototype.click=function(){downloads.push({name:this.download,blob:blobs.get(this.href)});};
class TestWorker{constructor(url){this.url=url;this.stopped=false;}terminate(){this.stopped=true;}async postMessage(data){try{const source=await blobs.get(this.url).text();const context=vm.createContext({postMessage:result=>{if(!this.stopped)this.onmessage?.({data:result});}});vm.runInContext(source,context);context.onmessage({data});}catch(e){this.onerror?.(e);}}}
w.Worker=TestWorker;
for(const file of ['engine.js','export.js','app.js'])vm.runInContext(fs.readFileSync(path.join(root,file),'utf8'),dom.getInternalVMContext());
const get=id=>w.document.getElementById(id);let checks=0;function pass(name){checks++;console.log('PASS '+name);}
const evaluate=code=>vm.runInContext(code,dom.getInternalVMContext()),text=id=>get(id).textContent;
(async()=>{
  assert.equal(get('page-playground').hidden,false);assert(text('keyword-preview').includes('say'));pass('initial studio state and local assets');
  for(const file of ['style.css','engine.js','export.js','app.js','assets/robot.png','assets/guide.png','assets/Jakarta.ttf','assets/Mono.ttf'])assert(fs.existsSync(path.join(root,file)));
  const expectations={welcome:['Hello, Josiah!','Welcome to my own language.'],loop:['Step 1','Step 2','Step 3','Step 4','Step 5','You made it!'],condition:['You did it!'],input:['What is your name?','How old are you?','Nice to meet you, Josiah!','Next year you will be 20.'],function:['4 squared = 16','9 squared = 81'],list:['Imagine','Create','Run']};
  for(const [name,expected]of Object.entries(expectations)){evaluate(`loadExample('${name}',true)`);const result=await evaluate('runProgram()');assert(result.ok,result.message);assert.deepEqual([...result.output],expected);assert.equal(get('run').hidden,false);assert(text('execution-status').startsWith('Completed'));pass('example '+name+' runs through visible worker flow');}
  evaluate("navigate('rules')");assert.equal(get('keyword-fields').children.length,17);get('language-name').value='JosiahScript';get('language-extension').value='jsiah';get('kw-print').value='sol';get('kw-let').value='keep';get('rules-form').dispatchEvent(new w.Event('submit',{bubbles:true,cancelable:true}));assert(get('code').value.includes('keep ideas'));assert(get('code').value.includes('sol ideas'));assert.equal(text('filename'),'hello.jsiah');assert((await evaluate('runProgram()')).ok);pass('custom language rules rename real tokens and execute');
  evaluate("navigate('rules')");get('kw-print').value='keep';get('rules-form').dispatchEvent(new w.Event('submit',{bubbles:true,cancelable:true}));assert.equal(get('rules-error').hidden,false);assert.equal(evaluate('definition.keywords.print'),'sol');pass('duplicate rules show error without corrupting state');
  assert.equal(evaluate(`remap('say "say" # say', {print:'say'},{print:'sol'})`),'sol "say" # say');pass('rule migration preserves strings and comments');
  get('code').value='sol missing';const error=await evaluate('runProgram()');assert.equal(error.ok,false);assert(text('output').includes('Line 1'));pass('runtime errors are visible with line numbers');
  get('code').value='sol "Downloaded language works"';await evaluate('downloadKit()');assert.equal(downloads.at(-1).name,'jsiah-language-kit.zip');fs.writeFileSync(path.join(__dirname,'.export-check','ui-kit.zip'),Buffer.from(await downloads.at(-1).blob.arrayBuffer()));pass('download action creates a ZIP with the active language');
  get('download-definition').click();const definition=JSON.parse(await downloads.at(-1).blob.text());assert.equal(definition.keywords.print,'sol');assert.equal(definition.extension,'jsiah');pass('definition export matches applied rules');
  for(const page of ['playground','rules','examples','downloads','reference']){evaluate(`navigate('${page}')`);assert.equal(get('page-'+page).hidden,false);assert.equal([...w.document.querySelectorAll('.page')].filter(el=>!el.hidden).length,1);}pass('all navigation views and guide content');
  evaluate('saveDraft()');await new Promise(r=>setTimeout(r,420));const saved=JSON.parse(w.localStorage.getItem('langlab-draft-v1'));assert.equal(saved.definition.name,'JosiahScript');assert(saved.code.includes('Downloaded language works'));pass('temporary browser draft records code and rules');
  // Exercise the generated offline page, including its embedded worker program.
  const html=evaluate("LangLabExport.offlineHTML(definition, 'sol \"Offline works\"', '')");assert(html.includes('JosiahScript'));
  const engine=fs.readFileSync(path.join(root,'engine.js'),'utf8');const exported=require('../dist/export.js').offlineHTML(definition,'sol "Offline works"',engine);const offline=new JSDOM(exported,{runScripts:'outside-only',url:'file:///RUN.html'});const ow=offline.window;ow.Blob=Blob;ow.URL.createObjectURL=w.URL.createObjectURL;ow.URL.revokeObjectURL=()=>{};ow.Worker=TestWorker;ow.eval(exported.match(/<script>([\s\S]*)<\/script>/)[1]);ow.document.getElementById('run').click();await new Promise(r=>setTimeout(r,20));assert.equal(ow.document.getElementById('output').textContent,'Offline works');assert.match(ow.document.getElementById('status').textContent,/Completed/);pass('offline file runner executes its self-contained worker');
  console.log(`\n${checks} DOM interaction and offline-runner checks passed. No visual browser QA was performed.`);offline.window.close();dom.window.close();
})().catch(error=>{console.error(error);dom.window.close();process.exitCode=1;});
