'use strict';
const assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),vm=require('node:vm'),{spawnSync}=require('node:child_process');
const engine=require('../dist/engine.js'),exporter=require('../dist/export.js');
const def={name:'Nova',extension:'nova',keywords:{...engine.defaults}};
const run=(code,input='',d=def)=>engine.execute(code,d,input).output;
let checks=0;function check(name,fn){fn();checks++;console.log('PASS '+name);}
check('strings, variables and arithmetic',()=>assert.deepEqual(run('let x = 2 + 3 * 4\nsay "Total " + text(x)\nsay 2 ** 3 ** 2'),['Total 14','512']));
check('comments and escapes',()=>assert.deepEqual(run('say "# not a comment" # comment\nsay "hello\\nworld"'),['# not a comment','hello\nworld']));
check('branching and logical operators',()=>assert.deepEqual(run('when 3 < 4 and not false\n say "yes"\notherwise\n say "no"\nend\nsay true or missing'),['yes','true']));
check('repeat with enclosing assignment',()=>assert.deepEqual(run('let i=0\nrepeat 4\n let n=2\n i=i+n\nend\nsay i'),['8']));
check('while and lists',()=>assert.deepEqual(run('let xs=[2,4,6]\nlet i=0\nwhile i<len(xs)\n say xs[i]\n i=i+1\nend'),['2','4','6']));
check('for loop with range and lists',()=>assert.deepEqual(run('let total=0\nfor x in [10, 20, 30]\n total=total+x\nend\nsay total\nlet squares=[]\nfor n in range(1, 4)\n push(squares, n * n)\nend\nsay join(squares, "-")'),['60','1-4-9']));
check('for loop over text',()=>assert.deepEqual(run('let letters=[]\nfor ch in "abc"\n push(letters, upper(ch))\nend\nsay join(letters, "")'),['ABC']));
check('functions, nested returns and recursion',()=>assert.deepEqual(run('fn factorial(n)\n when n <= 1\n  return 1\n end\n return n * factorial(n-1)\nend\nsay factorial(5)'),['120']));
check('input and numeric conversion',()=>assert.deepEqual(run('let who=ask("Name?")\nlet age=number(ask())\nsay who+" "+text(age+1)','Josiah\n19'),['Name?','Josiah 20']));
check('built-in helpers',()=>assert.deepEqual(run('say round(2.6)\nsay sqrt(81)\nsay abs(-3)\nsay min(2,7)\nsay max(2,7)\nsay "abc"[1]'),['3','9','3','2','7','b']));
check('extended built-in helpers',()=>assert.deepEqual(run('let words = split("hello world", " ")\nsay upper(words[0])\nsay lower("LANG")\nsay floor(3.9)\nsay ceil(3.1)\nsay reverse("cat")\nsay contains([1,2,3], 2)\nsay contains("hello", "ell")\nlet arr = [10, 20]\nlet last = pop(arr)\nsay last\nsay len(arr)'),['HELLO','lang','3','4','tac','true','true','20','1']));
check('custom keywords including Tamil marks',()=>{const d={name:'Mozhi',extension:'mozhi',keywords:{...def.keywords,print:'சொல்',let:'வை',if:'என்றால்',end:'முடி',for:'ஒவ்வொன்றாக',in:'இல்'}};assert.equal(engine.validate(d).length,0);assert.deepEqual(run('வை பெயர் = "Josiah"\nஎன்றால் true\n சொல் பெயர்\nமுடி\nவை கூட்டு = 0\nஒவ்வொன்றாக எண் இல் range(1, 4)\n கூட்டு = கூட்டு + எண்\nமுடி\nசொல் கூட்டு','',d),['Josiah','6']);});
check('duplicate keywords rejected',()=>assert(engine.validate({...def,keywords:{...def.keywords,print:'let'}}).length));
check('invalid extension rejected',()=>assert(engine.validate({...def,extension:'../bad'}).length));
check('line-aware error',()=>assert.throws(()=>run('say "hello"\nsay missing'),e=>e.line===2&&e.output[0]==='hello'));
check('division by zero rejected',()=>assert.throws(()=>run('say 2 / 0'),/divide by zero/));
check('missing input rejected',()=>assert.throws(()=>run('say ask()'),/Input is empty/));
check('invalid index rejected',()=>assert.throws(()=>run('say [1,2][3]'),/outside/));
check('bad function arity rejected',()=>assert.throws(()=>run('fn f(a)\n return a\nend\nsay f()'),/Expected 1/));
check('host APIs are inaccessible',()=>assert.throws(()=>run('say process'),/not defined/));
check('member access is rejected',()=>assert.throws(()=>run('say text.constructor'),/Unexpected character/));
check('infinite loops stopped',()=>assert.throws(()=>run('while true\nend'),/Execution limit/));
check('recursive calls stopped',()=>assert.throws(()=>run('fn f()\n return f()\nend\nf()'),/call limit/));
check('top-level return rejected',()=>assert.throws(()=>run('return 1'),/inside a function/));
check('block scoping',()=>assert.throws(()=>run('when true\n let inside=1\nend\nsay inside'),/not defined/));
check('unterminated block rejected',()=>assert.throws(()=>run('repeat 1\n say 2'),/Close this block/));
const engineSource=fs.readFileSync(path.join(__dirname,'../dist/engine.js'),'utf8');
const program='let name=ask("Name?")\nsay "Hello, "+name';
const files=exporter.kitFiles(def,program,engineSource,'Josiah');
const tmp=path.join(__dirname,'.export-check');fs.mkdirSync(tmp,{recursive:true});for(const [name,content]of Object.entries(files))fs.writeFileSync(path.join(tmp,name),content);
check('downloaded CLI runs actual custom program',()=>{const r=spawnSync(process.execPath,['cli.cjs','hello.nova','--input','input.txt'],{cwd:tmp,encoding:'utf8'});assert.equal(r.status,0,r.stderr);assert.equal(r.stdout,'Name?\nHello, Josiah\n');});
check('downloaded CLI returns nonzero on errors',()=>{fs.writeFileSync(path.join(tmp,'bad.nova'),'say missing');const r=spawnSync(process.execPath,['cli.cjs','bad.nova'],{cwd:tmp,encoding:'utf8'});assert.equal(r.status,1);assert.match(r.stderr,/Line 1/);});
const html=files['RUN.html'],inline=html.match(/<script>([\s\S]*)<\/script>/)[1];
check('offline runner script parses',()=>new vm.Script(inline));
check('offline runner embeds engine and saved input',()=>{assert(html.includes('initialInput="Josiah"'));assert(!/\ssrc=/.test(html));assert(!html.includes('fetch('));});
check('offline runner safely embeds hostile strings',()=>{const d={...def,name:'<script>alert(1)</script>'};const page=exporter.offlineHTML(d,'say "</script>"',engineSource);assert.equal((page.match(/<script>/g)||[]).length,1);assert.equal((page.match(/<\/script>/g)||[]).length,1);new vm.Script(page.match(/<script>([\s\S]*)<\/script>/)[1]);});
(async()=>{const bytes=await exporter.zip(files).arrayBuffer();fs.writeFileSync(path.join(tmp,'kit.zip'),Buffer.from(bytes));const r=spawnSync('python3',['-c','import zipfile,sys; z=zipfile.ZipFile(sys.argv[1]); assert z.testzip() is None; assert len(z.namelist())==8; assert z.read("input.txt").decode()=="Josiah"',path.join(tmp,'kit.zip')],{encoding:'utf8'});assert.equal(r.status,0,r.stderr);console.log('PASS download ZIP CRC, filenames, UTF-8, and contents');checks++;console.log(`\n${checks} runtime and export checks passed.`);})().catch(e=>{console.error(e);process.exitCode=1;});
